// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenEdAI.Data;

#nullable disable

namespace OpenEdAI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250224193858_UpdateDatabaseSchema")]
    partial class UpdateDatabaseSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("OpenEdAI.Models.Course", b =>
                {
                    b.Property<int>("CourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CourseID"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("StudentUserID")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("CourseID");

                    b.HasIndex("Owner");

                    b.HasIndex("StudentUserID");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("OpenEdAI.Models.CourseProgress", b =>
                {
                    b.Property<int>("ProgressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProgressID"));

                    b.Property<string>("CompletedLessonsJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LessonsCompleted")
                        .HasColumnType("int");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("StudentUserID")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ProgressID");

                    b.HasIndex("CourseID");

                    b.HasIndex("Owner");

                    b.HasIndex("StudentUserID");

                    b.ToTable("CourseProgress");
                });

            modelBuilder.Entity("OpenEdAI.Models.Lesson", b =>
                {
                    b.Property<int>("LessonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LessonID"));

                    b.Property<string>("ContentLink")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("LessonID");

                    b.HasIndex("CourseID");

                    b.HasIndex("Owner");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("OpenEdAI.Models.User", b =>
                {
                    b.Property<string>("UserID")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("OpenEdAI.Models.Student", b =>
                {
                    b.HasBaseType("OpenEdAI.Models.User");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("OpenEdAI.Models.Course", b =>
                {
                    b.HasOne("OpenEdAI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("Owner")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenEdAI.Models.Student", null)
                        .WithMany("Courses")
                        .HasForeignKey("StudentUserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OpenEdAI.Models.CourseProgress", b =>
                {
                    b.HasOne("OpenEdAI.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenEdAI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("Owner")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenEdAI.Models.Student", null)
                        .WithMany("ProgressRecords")
                        .HasForeignKey("StudentUserID");

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OpenEdAI.Models.Lesson", b =>
                {
                    b.HasOne("OpenEdAI.Models.Course", "Course")
                        .WithMany("Lessons")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenEdAI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("Owner")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OpenEdAI.Models.Course", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("OpenEdAI.Models.Student", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("ProgressRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
